"""Add rating columns to post table

Revision ID: 8080e8a7744d
Revises: 7e175d79db5a
Create Date: 2025-12-25 23:56:09.421453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8080e8a7744d'
down_revision = '7e175d79db5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rating_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('rating_count')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
